layout_spectrum: 0.15566625096835196
typography_spectrum: 0.47395565221086144
color:
  brandColors:
    - '#A4BCB4'
    - '#F2E76D'
    - '#1D201F'
    - '#5E6E6A'
    - '#748A85'
  brandStrength: 0.4198699160479009
  lightness: 0.2213427706155926
  saturation: 0.6726223542355001
  rhythmicContrast: 0.17270885640755296
name: Schack.dk
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-103530-15
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
