analytics:
  google: UA-103530-15
color:
  brandColors:
    - '#A4BCB4'
    - '#F2E76D'
    - '#1D201F'
    - '#5E6E6A'
    - '#748A85'
  brandStrength: 0.002878
  lightness: 0.424602
  rhythmicContrast: 0.397222
  saturation: 0.611847
cta: {}
layout_spectrum: 0.599506
name: Schack.dk
opengraph: {}
purpose: []
typography_spectrum: 1
