name: Schack.dk
favicon: null
layout_spectrum: 0.93734
typography_spectrum: 0.8104478649329394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-103530-15
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.125
  lightness: 0.42460269550792873
  saturation: 0.6118471887893975
  rhythmicContrast: 0.3972225687466562
purpose: []
